services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${LOCAL_POSTGRES_DB}
      POSTGRES_USER: ${LOCAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOCAL_POSTGRES_PASSWORD}
    ports:
      - '5435:5432'
